### ISSUE TITLE
Error In Payment 

### ISSUE THREAD

**Issue by GenIPTV** [bitpay/whmcs-plugin#42]
I tried accepting a payment with the bitpay plugin (installed from github)
in WHMCS 7.
It fails with the following error:
[ERROR] In modules/gateways/bitpay/createinvoice.php: Invalid invoice id #0

i see this topic before:
https://github.com/bitpay/whmcs-plugin/issues/25
but my problem continued yet :(

i have SSL domain and my currency is EUR

**Comment by big89** [comment]
Hello, yes we can help u for bitpay issue. We can provide u professional help.

**Comment by GenIPTV** [comment]
how u can help me?

**Comment by big89** [comment]
We already updated bitpay official module which is working with whmcs 7. Let me know if u want help for that.

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).

**Comment by stefanotto** [comment]
I still experience this with the latest plugin code.
Not sure how to reproduce it myself, since it's only happening every so often.

**Comment by stefanotto** [comment]
Ok, now it actually happens all the time. With existing and newly created clients as well after de- and reactivation of the gateway.
